/* generated by tools/extract-scene.mjs — do not edit by hand */
export interface SceneRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** every coordinate below is in reference pixels (1536 x 1024) */
export const SCENE_LAYOUT = {
  "reference": {
    "width": 1536,
    "height": 1024
  },
  "window": {
    "x": 310,
    "y": 190,
    "w": 920,
    "h": 534
  },
  "hits": {
    "menu": {
      "x": 92,
      "y": 826,
      "w": 92,
      "h": 92
    },
    "paytable": {
      "x": 192,
      "y": 826,
      "w": 100,
      "h": 92
    },
    "betMinus": {
      "x": 312,
      "y": 866,
      "w": 40,
      "h": 40
    },
    "betPlus": {
      "x": 462,
      "y": 866,
      "w": 40,
      "h": 40
    },
    "betValue": {
      "x": 348,
      "y": 838,
      "w": 118,
      "h": 66
    },
    "autoplay": {
      "x": 524,
      "y": 826,
      "w": 118,
      "h": 92
    },
    "spin": {
      "x": 676,
      "y": 800,
      "w": 158,
      "h": 158
    },
    "turbo": {
      "x": 878,
      "y": 826,
      "w": 116,
      "h": 92
    },
    "sound": {
      "x": 1258,
      "y": 18,
      "w": 56,
      "h": 56
    },
    "fullscreen": {
      "x": 1326,
      "y": 18,
      "w": 56,
      "h": 56
    },
    "info": {
      "x": 1394,
      "y": 18,
      "w": 56,
      "h": 56
    },
    "burger": {
      "x": 1462,
      "y": 18,
      "w": 56,
      "h": 56
    }
  },
  "values": {
    "balance": {
      "x": 18,
      "y": 40,
      "w": 190,
      "h": 44
    },
    "jp-mega": {
      "x": 74,
      "y": 225,
      "w": 150,
      "h": 31
    },
    "jp-major": {
      "x": 74,
      "y": 293,
      "w": 150,
      "h": 31
    },
    "jp-minor": {
      "x": 74,
      "y": 357,
      "w": 150,
      "h": 27
    },
    "jp-mini": {
      "x": 74,
      "y": 415,
      "w": 150,
      "h": 27
    },
    "freespins": {
      "x": 1322,
      "y": 206,
      "w": 160,
      "h": 62
    },
    "message": {
      "x": 520,
      "y": 733,
      "w": 500,
      "h": 40
    },
    "bet": {
      "x": 348,
      "y": 862,
      "w": 118,
      "h": 40
    },
    "win": {
      "x": 1040,
      "y": 862,
      "w": 210,
      "h": 46
    },
    "clock": {
      "x": 1442,
      "y": 988,
      "w": 86,
      "h": 30
    }
  }
} as const;
